### ISSUE TITLE
Генерация архива с Эклипсом с разными плагинами

### ISSUE THREAD

**Issue by aurusov** [aurusov/raox-deploy#1]
Предполагается
- перенести генерацию архива из https://github.com/aurusov/rdo-xtext
- добавить генерацию для https://github.com/aurusov/raox-game5

Генерация плагинов и архивов с плагинами остается в своих репах. Эта репа отвечает за архив с _Эклипсом_.

**Comment by AlexChernov** [comment]
А ведь это можно делать уже не мавеном.

**Comment by aurusov** [comment]
Можно. С мавеном возникли проблемы ?

**Comment by aurusov** [comment]
И давай генерить один архив и с рдо и с game5.

**Comment by aurusov** [comment]
Названия
- `raox-<version>.zip` - плагин (нет `plugin` в названии), уже в https://github.com/aurusov/rdo-xtext/pull/255
- `raox-game5-<version>.zip` - плагин, уже в https://github.com/aurusov/raox-game5/pull/51, коммит https://github.com/aurusov/raox-game5/commit/459332d543935ea65a8917365d11bd672a8f5386
- `raox-eclipse-<version>-<os>-<platform>.zip` - оба плагина + Эклипс

**Comment by AlexChernov** [comment]
> Можно. С мавеном возникли проблемы ?

Нет, просто могу на каком-нибудь питоне сделать скрипт, чтобы удобно читался. С другой стороны решение с помощью мавена можно сказать готово и работает, не придумал только как обеспечить гибкость сборки.
Т.е.

> raox-eclipse-<version>-<os>-<platform>.zip - оба плагина + Эклипс

можно реализовать очень быстро. А вот реализовать запуск с параметром, в котором, например, через запятую будут указанны все артифакты, которые надо заархивировать, пока не получилось.

**Comment by aurusov** [comment]
Тогда давай через мавен, который вытаскивает плагины из локальной репы. Сразу все, а не через параметры.

**Comment by aurusov** [comment]
Обновил https://github.com/aurusov/raox-deploy/issues/1#issuecomment-152840074. Не хватает 3-го, про `eclipse`. Не забуть в этой задаче добавить.

**Comment by AlexChernov** [comment]
Не могу найти, как вытащить версию из плагина, для названия архива

**Comment by aurusov** [comment]
Если это наш зиповый, то из имени. Если это имя джарника, то он сам архив, у которого есть манифест.

**Comment by AlexChernov** [comment]
Я про то, как это сделать в maven`e. Не нашел ни как посмотреть версию у jar`ника из dependency, ни как работать с именем файла

**Comment by aurusov** [comment]
Думаю, что мавен умеет отдавать версию пакета из репы (локальной/удаленной). Это должно быть из коробки.

**Comment by aurusov** [comment]
Хочется вытаскивать джарники для архива из репы, и для плагинов тоже https://github.com/aurusov/rdo-xtext/issues/244

**Comment by aurusov** [comment]
Блокирующавя задача https://github.com/aurusov/rdo-xtext/issues/244
